# 
# Aidan Bird, 2021
#
# latex compiling makefile
#
# HOW TO USE
# figures are generated by octave
# each figure has a octave script file (.m)
# the output of each file is a tex file (.tex); put filenames in _FIGS
# the script and tex figure files only differ by extension
# 

DIR_PROJ_ROOT := $(shell pwd)
DIR_DATA := $(DIR_PROJ_ROOT)/data
DIR_FIGURE := $(DIR_PROJ_ROOT)/figures
DIR_SRC := $(DIR_PROJ_ROOT)/src
DIR_TMP := $(DIR_PROJ_ROOT)/tmp

OCTAVE = octave --no-gui --norc -q -H
TEX = pdflatex -halt-on-error
PDF_VIEWER = zathura
DOC_NAME = doc

# example: _FIGS = fig1.tex fig2.tex fig3.tex
_FIGS = 
FIGS = $(patsubst %,$(DIR_FIGURE)/%,$(_FIGS))

.SUFFIXES: .m .tex

all: document
	echo 'done compiling'
	$(PDF_VIEWER) $(DIR_TMP)/$(DOC_NAME).pdf &
	disown

document: $(FIGS)
	cd $(DIR_TMP)
	$(TEX) -output-directory=$(DIR_TMP) $(DIR_SRC)/$(DOC_NAME).tex

$(DIR_FIGURE)/%.tex: $(DIR_SRC)/%.m
	$(OCTAVE) $<

.PHONY: clean
clean:
	rm $(DIR_FIGURE)/*
	rm $(DIR_TMP)/*

